# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49df3b5cd125857a6ad1a3cc8b9b4a8439508eba9c9b4c0e5004e31ee89cf0e261dc07e8003a697241c54dac601a97081c74cf0847b0ec793a36f88422369f7f

test:
  secret_key_base: 72d9be8a03341c14fc110a23658c5ac7aab4cf3139cab08f92813bc430d77c134c24382db90eb41abb9402d03520390807170bcbe29b9a42af87b42e28d6d652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
